from setuptools import setup, find_packages

setup(
    name='rag_benchmark',
    version='0.1.1',
    packages=find_packages(exclude=['data', 'docs', 'examples','test']),
    install_requires=[
        "tclogger",
        "thefuzz",
        "openpyxl",
        "nltk",
        "numpy",
        "transformers",
        "openai",
        "accelerate",
        "joblib",
        "pandas",
        "pillow",
        "py",
        "pytest",
        "pytz",
        "PyYAML",
        "requests",
        "schema",
        "six",
        "tokenizers",
    ],
    author="BITCynthia",
    author_email="cynthia74326@outlook.com",
    description="A benchmark to evaluate performance of RAG (Retrieval-Augmented Generation)",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
)
